version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend


